### ISSUE TITLE
How is the Kinship Matrix computed

### ISSUE THREAD

**Issue by arose13** [sens/FaSTLMM.jl#4]
Hey folks, I love how simple and well written this implementation is. I was wonder how was your kinship matrix computed?

**Comment by sens** [comment]
The kinship matrix in the example dataset was provided by the `recla` dataset from the `lmmlite` R package.  The documentation states:

     These are data for a set of diversity outcross mice. The kinship
     matrix was calculated from MUGA array data, using the qtl2geno
     package.

 Data URL: http://phenome.jax.org/db/q?rtn=projects/projdet&reqprojid=285
