### ISSUE TITLE
How are p-values computed here

### ISSUE THREAD

**Issue by arose13** [sens/FaSTLMM.jl#5]
There seems to be that both p-values are not given nor are they computable with the data available. Is this true? Also if there is anything I can do to help compute them that would be fine.

Cheers

**Comment by sens** [comment]
They are computable, but are not computed at this time.  This is something we will work on. For the moment, we are working on making the code faster.

**Comment by arose13** [comment]
By that you mean the brent part of the optimisation step is slower than you want I assume?

**Comment by sens** [comment]
If you are doing large-scale genome scans, you want to organize the computations efficiently. That's what we are working on. The Brent part is pretty good, I think.
