### ISSUE TITLE
two rss function with the same argument list 

### ISSUE THREAD

**Issue by ChelseaTrotter** [sens/FaSTLMM.jl#7]
https://github.com/sens/FaSTLMM.jl/blob/b9cc59c299f28cc4968c8ac90cee52027e1fac27/src/wls.jl#L97
https://github.com/sens/FaSTLMM.jl/blob/b9cc59c299f28cc4968c8ac90cee52027e1fac27/src/wls.jl#L136

In `wls.jl`, there are two function called `rss` with the same signature, which one should we use?

**Comment by sens** [comment]
Resolved with pull request: https://github.com/sens/FaSTLMM.jl/pull/8
